services:
  - type: web
    name: airticles-landing
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
